'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {LayoutDashboard,BookOpen,Megaphone,Users,ShieldCheck,ClipboardList,Flag,History,Settings,Plus,ArrowUpLeft,LockKeyhole,Search,RefreshCw,Pin,Archive,Edit3,Check,Send,LogOut,ExternalLink,LoaderCircle} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Label} from '@/components/ui/label';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {modules,actions,statuses,emptyData,permissionKeys,type AppData,type Item,type Kind,type Member,type Role} from '@/lib/domain';
const nav=[['overview','نظرة عامة',LayoutDashboard],['rules','التعليمات والقوانين',BookOpen],['announcements','الإعلانات',Megaphone],['staff','الطاقم الإداري',Users],['roles','الرتب والصلاحيات',ShieldCheck],['reports','البلاغات والطلبات',Flag],['tasks','المهام',ClipboardList],['audit','سجل العمليات',History],['settings','إعدادات السيرفر',Settings]] as const;
const descriptions:Record<string,string>={overview:'متابعة العمل الإداري في Elite State، من مكان واحد.',rules:'مرجع الطاقم للقوانين وإجراءات التعامل داخل السيرفر.',announcements:'المستجدات والتعاميم، للجمهور المناسب.',staff:'أعضاء الطاقم، رتبهم، وحالة الوصول إلى اللوحة.',roles:'حدّد بدقة ما يستطيع كل إداري مشاهدته وتنفيذه.',reports:'متابعة الطلبات والبلاغات حتى إغلاقها.',tasks:'توزيع المسؤوليات ومتابعة الإنجاز.',audit:'تسلسل التغييرات الإدارية. آخر 100 عملية.',settings:'هوية السيرفر وروابطه الرسمية.'};
const date=(s:string)=>new Date(s).toLocaleString('ar-BH',{dateStyle:'medium',timeStyle:'short'});
function Field({label,children}: {label:string;children:ReactNode}){return <Label className="field"><span>{label}</span>{children}</Label>}
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:Record<string,string>;label:string}){return <Select dir="rtl" value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(options).map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
function Blank({title,description,icon:Icon=BookOpen}:{title:string;description:string;icon?:any}){return <Empty><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
function Status({item}:{item:Item}){return <span className={'pill status-'+item.status}>{statuses[item.kind][item.status]}</span>}
async function post(payload:unknown){const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'تعذّر الحفظ.');return d}
function ItemEditor({kind,item,data,onClose,onSaved}:{kind:Kind;item?:Item;data:AppData;onClose:()=>void;onSaved:()=>Promise<void>}){
 const content=kind==='rules'||kind==='announcements';
 const [form,setForm]=useState({title:item?.title??'',body:item?.body??'',category:item?.category??'عام',status:item?.status??(content?'draft':'open'),priority:item?.priority??'normal',assignee:item?.assignee??'none',due:item?.due??'',pinned:!!item?.pinned,audience:item?.audience??'all'});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const can=(p:string)=>data.permissions.includes(p);
 const put=(k:string,v:unknown)=>setForm(f=>({...f,[k]:v}));
 const roleAudience:string[]=form.audience==='all'?[]:JSON.parse(form.audience);
 const options=Object.fromEntries(Object.entries(statuses[kind]).filter(([s])=> (s!=='published'||can(kind+'.publish'))&&(s!=='archived'||can(kind+'.archive'))));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await post({action:'saveItem',kind,id:item?.id,version:item?.version,...form,audience:form.audience==='all'?'all':roleAudience,assignee:form.assignee==='none'?null:form.assignee});toast.success('تم حفظ السجل');await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent dir="rtl" className="editor-dialog"><DialogHeader className="text-right"><DialogTitle>{item?'تعديل السجل':'إضافة سجل'} · {modules[kind]}</DialogTitle><DialogDescription>الحقول بعلامة * مطلوبة. تبقى المدخلات محفوظة في النموذج عند حدوث خطأ.</DialogDescription></DialogHeader><form onSubmit={save} className="form-stack"><Field label="العنوان *"><Input required maxLength={160} value={form.title} onChange={e=>put('title',e.target.value)} placeholder={content?'مثال: تعليمات التعامل مع البلاغات':'وصف مختصر وواضح'}/></Field><Field label="التفاصيل *"><Textarea required maxLength={12000} rows={6} value={form.body} onChange={e=>put('body',e.target.value)} placeholder="اكتب التفاصيل هنا…"/></Field><div className="form-grid"><Field label="التصنيف"><Input value={form.category} maxLength={80} onChange={e=>put('category',e.target.value)}/></Field><Field label="الحالة"><Choice label="الحالة" value={form.status} onChange={v=>put('status',v)} options={options}/></Field></div>{content?<><Field label="من يستطيع مشاهدة المنشور؟"><Choice label="الجمهور" value={form.audience==='all'?'all':'selected'} onChange={v=>put('audience',v==='all'?'all':JSON.stringify([data.me?.roleId]))} options={{all:'جميع أعضاء الطاقم',selected:'رتب محددة'}}/></Field>{form.audience!=='all'&&<div className="role-choices">{data.roles.map(r=><label key={r.id} className="check-label"><Checkbox checked={roleAudience.includes(r.id)} onCheckedChange={c=>put('audience',JSON.stringify(c?[...roleAudience,r.id]:roleAudience.filter(x=>x!==r.id)))}/>{r.name}</label>)}</div>}{can(kind+'.publish')&&<label className="check-label"><Checkbox checked={form.pinned} onCheckedChange={c=>put('pinned',!!c)}/>تثبيت أعلى القائمة</label>}<p className="help">المالك ومن يملك صلاحية النشر يستطيعان مراجعة جميع سجلات القسم.</p></>:<><div className="form-grid"><Field label="الأولوية"><Choice label="الأولوية" value={form.priority} onChange={v=>put('priority',v)} options={{normal:'عادية',high:'مرتفعة',urgent:'عاجلة'}}/></Field><Field label="المسؤول"><Choice label="المسؤول" value={form.assignee} onChange={v=>put('assignee',v)} options={{none:'غير مسند',...Object.fromEntries(data.members.filter(m=>m.active&&(can(kind+'.view_all')||m.id===data.me?.id||m.id===item?.assignee)).map(m=>[m.id,m.name]))}}/></Field></div>{kind==='tasks'&&<Field label="الموعد النهائي"><Input type="date" value={form.due} onChange={e=>put('due',e.target.value)}/></Field>}</>}{error&&<p role="alert" className="error-box">{error}</p>}<DialogFooter><Button type="submit" disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<Check/>}{busy?'جارٍ الحفظ…':'حفظ السجل'}</Button><Button variant="outline" type="button" disabled={busy} onClick={onClose}>إلغاء</Button></DialogFooter></form></DialogContent></Dialog>
}
function MemberEditor({member,onClose,onSaved}:{member:Member;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(member.name),[active,setActive]=useState(!!member.active),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await post({action:'saveMember',id:member.id,name,active});toast.success('تم تحديث حالة الإداري');await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent dir="rtl"><DialogHeader><DialogTitle>إدارة وصول الإداري</DialogTitle><DialogDescription>الرتبة تُقرأ من Discord. تقدر توقف العضو محليًا حتى لو عنده رتبة مسموحة.</DialogDescription></DialogHeader><form onSubmit={save} className="form-stack"><Field label="الاسم الإداري"><Input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Discord User ID"><Input readOnly dir="ltr" value={member.discordId??'عضوية قديمة غير مرتبطة'}/></Field><label className="check-label"><Checkbox checked={active} onCheckedChange={c=>setActive(!!c)}/>إلغاء الإيقاف المحلي</label><p className="notice">إلغاء الإيقاف لا يمنح رتبة. يظل وجود العضو في السيرفر وحمله رتبة مرتبطة باللوحة شرطًا للدخول.</p>{error&&<p role="alert" className="error-box">{error}</p>}<Button disabled={busy} type="submit">{busy?'جارٍ الحفظ…':'حفظ حالة الإداري'}</Button></form></DialogContent></Dialog>
}
function RoleEditor({role,onClose,onSaved}:{role?:Role;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(role?.name??''),[perms,setPerms]=useState<string[]>(role?JSON.parse(role.permissions):[]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [discordRoleId,setDiscordRoleId]=useState(role?.discordRoleId??''),[priority,setPriority]=useState(role?.priority??100);
 const toggle=(p:string,c:unknown)=>setPerms(old=>c?[...old,p]:old.filter(x=>x!==p));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await post({action:'saveRole',id:role?.id,name,permissions:perms,discordRoleId,priority});toast.success('تم حفظ الصلاحيات');await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent dir="rtl" className="editor-dialog"><DialogHeader><DialogTitle>{role?'تعديل رتبة':'رتبة جديدة'}</DialogTitle><DialogDescription>صلاحيات الطاقم تُطبّق على الخادم. إدارة الرتب والعضوية للمالك فقط.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={save}><Field label="اسم الرتبة *"><Input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="form-grid"><Field label="Discord Role ID"><Input dir="ltr" inputMode="numeric" pattern="[0-9]{17,20}" maxLength={20} placeholder="الصق رقم الرتبة، وليس اسمها" value={discordRoleId} onChange={e=>setDiscordRoleId(e.target.value.trim())}/></Field><Field label="أولوية هذه الرتبة"><Input type="number" required min={0} max={1000} value={priority} onChange={e=>setPriority(Number(e.target.value))}/></Field></div><p className="notice">ترك Role ID فارغًا يلغي ربط هذه الرتبة. عند وجود عدة رتب للعضو، تُطبّق رتبة واحدة ذات الأولوية الأعلى، ولا تُجمع الصلاحيات. عند تساوي الأولوية يكون الترتيب حسب المعرّف الداخلي.</p><div className="permissions-matrix"><Table><TableHeader><TableRow><TableHead>القسم</TableHead>{Object.values(actions).map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{Object.entries(modules).map(([m,label])=><TableRow key={m}><TableCell>{label}</TableCell>{Object.keys(actions).map(a=>{const p=m+'.'+a;return <TableCell key={p}>{permissionKeys.includes(p)?<Checkbox aria-label={label+' '+actions[a as keyof typeof actions]} checked={perms.includes(p)} onCheckedChange={c=>toggle(p,c)}/>:'—'}</TableCell>})}</TableRow>)}</TableBody></Table></div><div className="role-choices">{[['staff.view','عرض دليل الطاقم'],['audit.view','عرض سجل العمليات'],['settings.edit','تعديل معلومات السيرفر']].map(([p,t])=><label className="check-label" key={p}><Checkbox checked={perms.includes(p)} onCheckedChange={c=>toggle(p,c)}/>{t}</label>)}</div><p className="help">دون «عرض جميع السجلات»، تظهر فقط البلاغات والمهام التي أنشأها الإداري أو أُسندت إليه. النشر يتطلب أيضًا العرض والإنشاء أو التعديل، والأرشفة تتطلب التعديل.</p>{error&&<p role="alert" className="error-box">{error}</p>}<Button type="submit" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ الرتبة'}</Button></form></DialogContent></Dialog>
}
function Details({item,data,onClose,onEdit,onArchive}:{item:Item;data:AppData;onClose:()=>void;onEdit:()=>void;onArchive:()=>void}){
 const [comments,setComments]=useState<any[]>([]),[body,setBody]=useState(''),[internal,setInternal]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const can=(p:string)=>data.permissions.includes(p),discussion=['tasks','reports'].includes(item.kind);
 const editable=can(item.kind+'.edit')&&(!['rules','announcements'].includes(item.kind)||item.status!=='published'||can(item.kind+'.publish'));
 async function load(){try{const r=await fetch('/api/admin?comments='+item.id);const d:any=await r.json();if(!r.ok)throw new Error(d.error);setComments(d)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(discussion)void load()},[item.id]);
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await post({action:'comment',id:item.id,body,internal});setBody('');await load();toast.success('تمت إضافة الرد')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent side="left" dir="rtl" className="detail-sheet"><SheetHeader><SheetTitle>{item.title}</SheetTitle><SheetDescription>{modules[item.kind]} · {item.category}</SheetDescription></SheetHeader><div className="detail-body"><div className="flex gap-2 flex-wrap"><Status item={item}/>{item.pinned===1&&<span className="pill"><Pin size={14}/>مثبت</span>}</div><p className="record-body">{item.body}</p><div className="metadata"><p>أنشأه: {data.members.find(m=>m.id===item.createdBy)?.name??'إداري'}</p><p>آخر تعديل: {date(item.updatedAt)}</p>{discussion&&<><p>المسؤول: {data.members.find(m=>m.id===item.assignee)?.name??'غير مسند'}</p><p>الأولوية: {{normal:'عادية',high:'مرتفعة',urgent:'عاجلة'}[item.priority]}</p>{item.due&&<p>الموعد النهائي: <span dir="ltr">{item.due}</span></p>}</>}{!discussion&&<p>الجمهور: {item.audience==='all'?'جميع أعضاء الطاقم':JSON.parse(item.audience).map((id:string)=>data.roles.find(r=>r.id===id)?.name??'رتبة').join('، ')}</p>}</div><div className="flex gap-2 flex-wrap">{editable&&<Button variant="outline" onClick={onEdit}><Edit3/>تعديل</Button>}{editable&&can(item.kind+'.archive')&&item.status!=='archived'&&<Button variant="ghost" onClick={onArchive}><Archive/>أرشفة</Button>}</div>{discussion&&<section className="discussion"><h2>المتابعة والردود</h2>{comments.length?comments.map(c=><article className={'comment '+(c.internal?'internal':'')} key={c.id}><div><strong>{c.actor}</strong>{!!c.internal&&<span className="pill">ملاحظة داخلية</span>}</div><p className="record-body">{c.body}</p><small className="muted">{date(c.createdAt)}</small></article>):<p className="muted">لا توجد ردود بعد.</p>}{item.status!=='archived'&&(can(item.kind+'.edit')||item.createdBy===data.me?.id)&&<form onSubmit={send} className="form-stack"><Field label="إضافة متابعة"><Textarea required maxLength={6000} value={body} onChange={e=>setBody(e.target.value)} placeholder="اكتب ردًا أو مستجدًا…"/></Field>{can(item.kind+'.view_all')&&<label className="check-label"><Checkbox checked={internal} onCheckedChange={c=>setInternal(!!c)}/>ملاحظة داخلية للإدارة فقط</label>}<Button type="submit" disabled={busy}><Send/>{busy?'جارٍ الإرسال…':'إضافة الرد'}</Button></form>}</section>}{error&&<p role="alert" className="error-box">{error}</p>}</div></SheetContent></Sheet>
}
function SettingsForm({data,onSaved}:{data:AppData;onSaved:()=>Promise<void>}){
 const [f,setF]=useState(data.settings),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="dashboard-grid"><section className="panel p-6"><h2>معلومات السيرفر</h2><form className="form-stack mt-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await post({action:'settings',...f});toast.success('تم حفظ الإعدادات');await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="اسم السيرفر *"><Input required maxLength={80} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="رابط Discord الرسمي"><Input type="url" dir="ltr" placeholder="https://discord.gg/…" value={f.discord} onChange={e=>setF({...f,discord:e.target.value})}/></Field><Field label="رابط الانضمام إلى FiveM"><Input type="url" dir="ltr" placeholder="https://cfx.re/join/…" value={f.connect} onChange={e=>setF({...f,connect:e.target.value})}/></Field>{error&&<p role="alert" className="error-box">{error}</p>}<Button disabled={busy} type="submit">{busy?'جارٍ الحفظ…':'حفظ الإعدادات'}</Button></form></section><section className="panel p-6"><ShieldCheck className="cyan mb-4" size={30}/><h2>الربط مع FiveM</h2><span className="pill mt-3">غير مفعّل</span><p className="muted mt-4">إضافة رابط الانضمام لا تربط بيانات السيرفر باللوحة. الربط المباشر يحتاج موردًا آمنًا على FiveM وإعدادات سيرفرك.</p><p className="notice mt-5">لا تضع كلمات مرور أو مفاتيح السيرفر في هذه الحقول.</p></section></div>
}
export default function AdminApp(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState<AppData>(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[editor,setEditor]=useState<{kind:Kind;item?:Item}|null>(null),[memberEditor,setMemberEditor]=useState<Member|null>(null),[roleEditor,setRoleEditor]=useState<Role|true|null>(null),[selected,setSelected]=useState<string|null>(null),[confirm,setConfirm]=useState<Item|null>(null),[busy,setBusy]=useState(false);
 const can=(p:string)=>data.permissions.includes(p);
 function clearPrivateData(){setData(emptyData);setEditor(null);setMemberEditor(null);setRoleEditor(null);setSelected(null);setConfirm(null)}
 async function logout(){setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw new Error('تعذّر تسجيل الخروج. حاول مجددًا.');clearPrivateData();window.location.assign('/login')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reload(){setError('');try{const r=await fetch('/api/admin',{cache:'no-store'});const d:any=await r.json();if(r.status===401){clearPrivateData();setAuth('login');return}if(r.status===403){clearPrivateData();setAuth(d.join?'join':'denied');setError(d.error);return}if(!r.ok)throw new Error(d.error);setAuth('');setData({...emptyData,...d})}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void reload();const change=()=>{const id=location.hash.slice(1);if(nav.some(n=>n[0]===id))setTab(id);setFilter('all');setQuery('')};change();window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[]);
 const go=(id:string)=>{setTab(id);setFilter('all');setQuery('');history.replaceState(null,'','#'+id)};
 const navAllowed=(id:string)=>id==='overview'||(id in modules?can(id+'.view'):id==='roles'?can('roles.manage'):id==='staff'?can('staff.view')||can('staff.manage'):id==='audit'?can('audit.view'):can('settings.edit'));
 const shownNav=data.me?nav.filter(n=>navAllowed(n[0])):[];
 const activeTitle=nav.find(n=>n[0]===tab)?.[1];
 const current=selected?data.items.find(i=>i.id===selected):undefined;
 const filtered=data.items.filter(i=>i.kind===tab&&(filter==='all'?i.status!=='archived':filter==='pinned'?!!i.pinned&&i.status!=='archived':i.status===filter)&&[i.title,i.body,i.category].join(' ').toLowerCase().includes(query.toLowerCase()));
 const membersFiltered=data.members.filter(m=>(m.name+' '+(m.discordId??'')).toLowerCase().includes(query.toLowerCase()));
 const primary=tab in modules&&can(tab+'.create');
 async function setup(action:string){setBusy(true);try{await post({action});await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const latest=data.items.filter(i=>i.kind==='announcements'&&i.status==='published').slice(0,3);
 const stats:[Kind,string,any][]=[['rules','التعليمات المنشورة',BookOpen],['announcements','الإعلانات المنشورة',Megaphone],['reports','البلاغات المفتوحة',Flag],['tasks','المهام الجارية',ClipboardList]];
 function rows(items:Item[]){return items.map(i=><button className="record-row" key={i.id} onClick={()=>setSelected(i.id)}><div className="record-main"><div className="flex gap-2 items-center"><strong>{i.title}</strong>{!!i.pinned&&<Pin size={14} className="cyan"/>}</div><small>{i.category} · {date(i.updatedAt)}</small></div><Status item={i}/><ArrowUpLeft size={17}/></button>)}
 return <SidebarProvider><Toaster dir="rtl" position="bottom-center" richColors/><Sidebar side="right"><SidebarHeader className="brand"><img src="/elite-logo.png" alt="شعار Elite State" className="brand-mark"/><div><strong dir="ltr">ELITE STATE</strong><small>CFW · بوابة الإدارة</small></div></SidebarHeader><SidebarContent className="nav-area"><p className="eyebrow">مساحة العمل</p><SidebarMenu>{shownNav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={tab===id} onClick={()=>go(id)} className="nav-item"><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="sidebar-foot"><span className="avatar">{data.me?.name?.slice(0,1)||'EL'}</span><div className="min-w-0 flex-1"><strong className="block truncate">{data.me?.name||'Elite State'}</strong><small>{data.roles.find(r=>r.id===data.me?.roleId)?.name||'مساحة إدارة خاصة'}</small></div>{data.me&&<button onClick={()=>void logout()} disabled={busy} aria-label="تسجيل الخروج"><LogOut size={18}/></button>}</SidebarFooter></Sidebar><SidebarInset className="min-w-0"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger aria-label="إظهار القائمة"/><span>مركز الإدارة</span><span className="separator">/</span><strong>{activeTitle}</strong></div><div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>void reload()} aria-label="تحديث البيانات"><RefreshCw size={17}/></Button><span className="pill"><LockKeyhole size={14}/>وصول محمي</span></div></header><div className="workspace">
 {auth==='login'?<section className="panel login-panel"><img src="/elite-banner.png" alt="Elite State"/><div><LockKeyhole className="cyan" size={30}/><h1>مركز إدارة Elite State</h1><p className="muted">سجّل دخولك بواسطة Discord. بيانات الإدارة متاحة فقط لأصحاب رتب السيرفر التي اعتمدها المالك.</p><Button asChild className="mt-5"><a href="/login">الدخول بواسطة Discord</a></Button></div></section>:data.setup?<section className="panel login-panel"><img src="/elite-banner.png" alt="Elite State"/><div><h1>جهّز مساحة إدارتك</h1><p className="muted">ابدأ بحساب Discord الخاص بالمالك. سنجهّز الرتب المطلوبة بصلاحيات مبدئية، وتربط كل رتبة برقمها من قسم الرتب والصلاحيات.</p><p className="help mt-4">التأسيس متاح لرقم حساب المالك المحدد في الاستضافة. الرتب غير المرتبطة لا تمنح وصولًا، حتى لو تطابقت أسماؤها في Discord.</p><Button className="mt-5" onClick={()=>setup('setup')} disabled={busy}>{busy?'جارٍ التجهيز…':'تأسيس لوحة Elite State'}</Button></div></section>:auth==='join'||auth==='denied'?<section className="panel p-8"><h1>{auth==='join'?'رتبتك مؤهلة للدخول':'تحتاج رتبة Discord مسموحة'}</h1><p className="muted">الوصول يتطلب عضويتك في السيرفر ورتبة مرتبطة باللوحة. إذا تغيّرت رتبتك، اضغط تحديث البيانات. الإيقاف المحلي يمنع الدخول أيضًا.</p>{auth==='join'&&<Button className="mt-5" disabled={busy} onClick={()=>setup('join')}>تفعيل العضوية والدخول</Button>}<button className="inline-block m-4 cyan" disabled={busy} onClick={()=>void logout()}>تسجيل الخروج / تغيير الحساب</button></section>:<>
 <div className="page-heading"><div><p className="eyebrow cyan">ELITE STATE CFW</p><h1>{activeTitle}</h1><p className="muted">{descriptions[tab]}</p></div>{primary?<Button onClick={()=>setEditor({kind:tab as Kind})}><Plus/>إضافة سجل</Button>:tab==='overview'&&can('announcements.create')?<Button onClick={()=>setEditor({kind:'announcements'})}><Plus/>إعلان جديد</Button>:tab==='staff'&&data.me?.roleId==='owner'?<Button onClick={()=>go('roles')}><ShieldCheck/>ربط رتب Discord</Button>:tab==='roles'&&data.me?.roleId==='owner'?<Button onClick={()=>setRoleEditor(true)}><Plus/>رتبة جديدة</Button>:null}</div>
 {loading?<div className="stats">{[1,2,3,4].map(i=><Skeleton className="h-36" key={i}/>)}</div>:data.me&&!navAllowed(tab)?<Blank title="القسم غير متاح لرتبتك" description="اطلب من مالك اللوحة مراجعة صلاحياتك." icon={LockKeyhole}/>:data.me&&<>
 {tab==='overview'&&<><div className="stats">{stats.filter(([k])=>can(k+'.view')).map(([k,label,Icon])=><button className="stat text-right" key={k} onClick={()=>go(k)}><span className="stat-icon"><Icon size={21}/></span><p>{label}</p><strong>{data.items.filter(i=>i.kind===k&&(['rules','announcements'].includes(k)?i.status==='published':['open','progress'].includes(i.status))).length}</strong><small>ضمن صلاحياتك</small></button>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>الإعلانات الأخيرة</h2>{can('announcements.view')&&<Button variant="ghost" onClick={()=>go('announcements')}>عرض الكل<ArrowUpLeft size={16}/></Button>}</div>{latest.length?rows(latest):<Blank icon={Megaphone} title="لا توجد إعلانات منشورة" description={can('announcements.create')?'أضف أول تعميم وحدّد الرتب التي يمكنها مشاهدته.':'ستظهر هنا الإعلانات المنشورة المتاحة لرتبتك.'}/>}</section><section className="panel server-card"><img src="/elite-banner.png" alt="Elite State" className="server-banner"/><div className="server-details"><div className="flex gap-2 flex-wrap items-center justify-between"><h2 dir="ltr">{data.settings.name}</h2><span className="pill muted">FiveM غير متصل</span></div><p className="muted">اللوحة الإدارية جاهزة للعمل بشكل مستقل عن اللعبة.</p><div className="flex gap-3 mt-4">{data.settings.discord&&<a className="text-link" href={data.settings.discord} target="_blank" rel="noopener noreferrer">Discord <ExternalLink size={14}/></a>}{data.settings.connect&&<a className="text-link" href={data.settings.connect} target="_blank" rel="noopener noreferrer">دخول السيرفر <ExternalLink size={14}/></a>}</div></div></section><section className="panel"><div className="panel-heading"><h2>يحتاج متابعة</h2><span className="muted">البلاغات والمهام</span></div>{data.items.some(i=>['tasks','reports'].includes(i.kind)&&['open','progress'].includes(i.status))?rows(data.items.filter(i=>['tasks','reports'].includes(i.kind)&&['open','progress'].includes(i.status)).slice(0,4)):<Blank title="لا توجد أعمال معلّقة" description="ستظهر المهام والبلاغات المفتوحة هنا." icon={ClipboardList}/>}</section><section className="panel"><div className="panel-heading"><h2>{can('audit.view')?'آخر العمليات':'التعليمات المثبتة'}</h2><History size={18}/></div>{can('audit.view')?<div className="activity-list">{data.audit.slice(0,4).map(a=><div className="activity" key={a.id}><span className="activity-line"/><div><strong>{a.action}</strong><p>{a.target}</p><small>{a.actor} · {date(a.createdAt)}</small></div></div>)}</div>:rows(data.items.filter(i=>i.kind==='rules'&&i.pinned&&i.status==='published').slice(0,3))}</section></div></>}
 {tab in modules&&<><div className="toolbar"><div className="search-box"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالعنوان أو التفاصيل…" aria-label="بحث السجلات"/></div><Tabs dir="rtl" value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">الكل</TabsTrigger>{['rules','announcements'].includes(tab)&&<TabsTrigger value="pinned">المثبتة</TabsTrigger>}{Object.entries(statuses[tab as Kind]).map(([v,l])=><TabsTrigger value={v} key={v}>{l}</TabsTrigger>)}</TabsList></Tabs></div><section className="panel"><div className="panel-heading"><h2>{filtered.length} سجلات</h2><span className="muted">الأحدث أولًا · المثبت في الأعلى</span></div>{filtered.length?rows(filtered):<Blank icon={nav.find(n=>n[0]===tab)?.[2]} title={query?'لا توجد نتائج مطابقة':'لا توجد سجلات هنا بعد'} description={query?'جرّب كلمة أخرى أو غيّر التصفية.':'ابدأ بإضافة سجل، أو غيّر التصفية لعرض الأرشيف.'}/>}</section></>}
 {tab==='staff'&&<><p className="notice mb-5">منح رتبة Discord مرتبطة باللوحة يسمح بالدخول. هذه القائمة تسجل آخر تحقق ناجح لكل عضو، وليست مزامنة مباشرة لجميع أعضاء Discord. الإيقاف هنا منع إضافي مستقل عن الرتبة.</p><div className="search-box mb-5"><Search size={18}/><Input aria-label="بحث الطاقم" placeholder="ابحث عن إداري…" value={query} onChange={e=>setQuery(e.target.value)}/></div><section className="panel"><Table><TableHeader><TableRow><TableHead>الإداري</TableHead><TableHead>الرتبة</TableHead><TableHead>الحالة</TableHead><TableHead>الإجراء</TableHead></TableRow></TableHeader><TableBody>{membersFiltered.map(m=><TableRow key={m.id}><TableCell><strong>{m.name}</strong>{m.discordId&&<small className="block muted" dir="ltr">{m.discordId}</small>}{m.lastVerifiedAt&&<small className="block muted">آخر تحقق: {date(m.lastVerifiedAt)}</small>}</TableCell><TableCell>{data.roles.find(r=>r.id===m.roleId)?.name}</TableCell><TableCell><span className="pill">{!m.active?'موقوف محليًا':'غير موقوف محليًا'}</span></TableCell><TableCell>{data.me?.roleId==='owner'&&m.roleId!=='owner'?<Button variant="ghost" onClick={()=>setMemberEditor(m)}>تعديل</Button>:<span className="muted">—</span>}</TableCell></TableRow>)}</TableBody></Table>{!membersFiltered.length&&<Blank title="لا توجد نتائج" description="جرّب اسمًا آخر." icon={Users}/>}</section></>}
 {tab==='roles'&&<div className="role-grid">{data.roles.map(r=><section key={r.id} className="panel role-card"><div className="flex justify-between items-start"><ShieldCheck className="cyan" size={28}/>{r.id==='owner'&&<span className="pill">رتبة محمية</span>}</div><h2>{r.name}</h2><p className="muted">{data.members.filter(m=>m.roleId===r.id&&m.active).length} أعضاء فعّالين</p>{r.id!=='owner'&&<><p className="help mt-3">{r.discordRoleId?'مرتبطة بـDiscord':'غير مرتبطة — لا تمنح دخولًا'}</p>{r.discordRoleId&&<p className="help" dir="ltr">{r.discordRoleId}</p>}<p className="help">الأولوية: {r.priority}</p></>}<div className="role-tags">{r.id==='owner'?<span>جميع الصلاحيات</span>:Object.entries(modules).filter(([m])=>JSON.parse(r.permissions).includes(m+'.view')).map(([m,t])=><span key={m}>{t}</span>)}</div><p className="help">{r.id==='owner'?'لا يمكن إيقاف المالك أو تعديل رتبته.':JSON.parse(r.permissions).length+' صلاحية مفعّلة'}</p>{r.id!=='owner'&&<Button className="w-full mt-5" variant="outline" onClick={()=>setRoleEditor(r)}><Edit3 size={16}/>تعديل الصلاحيات</Button>}</section>)}</div>}
 {tab==='audit'&&<section className="panel"><Table><TableHeader><TableRow><TableHead>العملية</TableHead><TableHead>السجل</TableHead><TableHead>الإداري</TableHead><TableHead>التوقيت</TableHead></TableRow></TableHeader><TableBody>{data.audit.map(a=><TableRow key={a.id}><TableCell>{a.action}</TableCell><TableCell>{a.target}</TableCell><TableCell>{a.actor}</TableCell><TableCell className="muted">{date(a.createdAt)}</TableCell></TableRow>)}</TableBody></Table><p className="help p-5">السجل للقراءة فقط، ولا يمكن حذفه أو تعديله من اللوحة.</p></section>}
 {tab==='settings'&&<SettingsForm data={data} onSaved={reload}/>}
 </>}</>}
 {error&&<div className="error-box mt-5" role="alert">{error}<Button variant="ghost" onClick={()=>void reload()}>إعادة المحاولة</Button></div>}
 <footer className="workspace-footer"><span>Elite State CFW</span><span>الإدارة · FiveM</span></footer></div></SidebarInset>
 {editor&&<ItemEditor key={editor.item?.id??editor.kind} {...editor} data={data} onClose={()=>setEditor(null)} onSaved={reload}/>}
 {memberEditor&&<MemberEditor member={memberEditor} onClose={()=>setMemberEditor(null)} onSaved={reload}/>}
 {roleEditor&&<RoleEditor role={roleEditor===true?undefined:roleEditor} onClose={()=>setRoleEditor(null)} onSaved={reload}/>}
 {current&&!editor&&<Details item={current} data={data} onClose={()=>setSelected(null)} onEdit={()=>setEditor({kind:current.kind,item:current})} onArchive={()=>setConfirm(current)}/>}
 <AlertDialog open={!!confirm} onOpenChange={v=>!v&&!busy&&setConfirm(null)}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>أرشفة السجل؟</AlertDialogTitle><AlertDialogDescription>سينتقل «{confirm?.title}» إلى الأرشيف. يمكنك استعادته بتعديل حالته لاحقًا.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>إلغاء</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(!confirm)return;setBusy(true);try{await post({action:'saveItem',...confirm,status:'archived',audience:confirm.audience==='all'?'all':JSON.parse(confirm.audience),pinned:false});setConfirm(null);setSelected(null);await reload();toast.success('تمت الأرشفة')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>{busy?'جارٍ الأرشفة…':'نعم، أرشفة'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}
